FROM node:10.15.3-stretch
ARG NODE_ENV=production

#RUN apt update && apt install -y zip

WORKDIR /app
COPY . .

RUN npm install
RUN npm install -g serve
RUN npm run build:production

EXPOSE 3000

CMD [ "serve", "-s", "build"]
